-- riscv-tests conformance: assemble each allowlisted .s, run the Hart to halt,
-- assert tohost == 1 (ADR-0004). The allowlist grows as later slices implement
-- more instructions, keeping the gate green every slice.
local asm = require("asm")
local Mem = require("mem")
local Hart = require("hart")

local FIXTURES = "spec/fixtures/riscv-tests/"
local VFIXTURES = "spec/fixtures/riscv-vector-tests/"

-- ponytail: the allowlist grows one slice at a time. Slices #5-#6 add the
-- load/store and control-flow fixtures; #9 adds rv32um (M extension).
local ALLOW = {
  -- #3 walking skeleton + #4 RV32I ALU (reg-reg, reg-imm, lui, auipc)
  "rv32ui-p-simple",
  "rv32ui-p-add",
  "rv32ui-p-addi",
  "rv32ui-p-sub",
  "rv32ui-p-and",
  "rv32ui-p-andi",
  "rv32ui-p-or",
  "rv32ui-p-ori",
  "rv32ui-p-xor",
  "rv32ui-p-xori",
  "rv32ui-p-sll",
  "rv32ui-p-slli",
  "rv32ui-p-srl",
  "rv32ui-p-srli",
  "rv32ui-p-sra",
  "rv32ui-p-srai",
  "rv32ui-p-slt",
  "rv32ui-p-slti",
  "rv32ui-p-sltu",
  "rv32ui-p-sltiu",
  "rv32ui-p-lui",
  "rv32ui-p-auipc",
  -- #5 RV32I load/store (misaligned handled in-hardware, not trapped)
  "rv32ui-p-lb",
  "rv32ui-p-lbu",
  "rv32ui-p-lh",
  "rv32ui-p-lhu",
  "rv32ui-p-lw",
  "rv32ui-p-sb",
  "rv32ui-p-sh",
  "rv32ui-p-sw",
  "rv32ui-p-ld_st",
  "rv32ui-p-st_ld",
  "rv32ui-p-ma_data",
  -- #6 RV32I control flow (branches + jumps); fence_i is a nop for one hart
  "rv32ui-p-beq",
  "rv32ui-p-bne",
  "rv32ui-p-blt",
  "rv32ui-p-bge",
  "rv32ui-p-bltu",
  "rv32ui-p-bgeu",
  "rv32ui-p-jal",
  "rv32ui-p-jalr",
  "rv32ui-p-fence_i",
  -- #9 M extension
  "rv32um-p-mul",
  "rv32um-p-mulh",
  "rv32um-p-mulhsu",
  "rv32um-p-mulhu",
  "rv32um-p-div",
  "rv32um-p-divu",
  "rv32um-p-rem",
  "rv32um-p-remu",
  -- #7 M-mode CSR/trap core: mret, mstatus/MPP, illegal trap, misa/mhartid.
  -- The misalign-trap variants (ma_addr, *-misaligned) conflict with the
  -- already-green rv32ui ma_data, and pmpaddr/breakpoint/instret_overflow/
  -- zicntr need out-of-scope extensions -- both groups stay descoped.
  "rv32mi-p-csr",
  "rv32mi-p-mcsr",
  "rv32mi-p-scall",
  "rv32mi-p-sbreak",
  "rv32mi-p-shamt",
}

-- Zve32x conformance: riscv-vector-tests fixtures (ADR-0012), same pipeline,
-- separate allowlist -- it grows per instruction family until the full zve32x
-- preset is green (#37..#47; the ship gate lives in #47). Families list every
-- split file the vendor command produced for that mnemonic.
local VFAMILIES = {
  -- #37 walking skeleton
  { "vadd_vv", 2 },
  -- #39 single-width integer arithmetic
  { "vadd_vi", 4 },
  { "vadd_vx", 5 },
  { "vsub_vv", 2 },
  { "vsub_vx", 7 },
  { "vrsub_vi", 4 },
  { "vrsub_vx", 5 },
  { "vadc_vim", 2 },
  { "vadc_vvm", 1 },
  { "vadc_vxm", 3 },
  { "vmadc_vi", 2 },
  { "vmadc_vim", 2 },
  { "vmadc_vv", 1 },
  { "vmadc_vvm", 1 },
  { "vmadc_vx", 3 },
  { "vmadc_vxm", 3 },
  { "vsbc_vvm", 1 },
  { "vsbc_vxm", 4 },
  { "vmsbc_vv", 1 },
  { "vmsbc_vvm", 1 },
  { "vmsbc_vx", 3 },
  { "vmsbc_vxm", 3 },
  { "vand_vi", 4 },
  { "vand_vv", 2 },
  { "vand_vx", 5 },
  { "vor_vi", 4 },
  { "vor_vv", 2 },
  { "vor_vx", 5 },
  { "vxor_vi", 4 },
  { "vxor_vv", 2 },
  { "vxor_vx", 5 },
  { "vsll_vi", 4 },
  { "vsll_vv", 2 },
  { "vsll_vx", 5 },
  { "vsrl_vi", 4 },
  { "vsrl_vv", 2 },
  { "vsrl_vx", 5 },
  { "vsra_vi", 4 },
  { "vsra_vv", 2 },
  { "vsra_vx", 5 },
  { "vmseq_vi", 4 },
  { "vmseq_vv", 2 },
  { "vmseq_vx", 5 },
  { "vmsne_vi", 4 },
  { "vmsne_vv", 2 },
  { "vmsne_vx", 5 },
  { "vmsltu_vv", 2 },
  { "vmsltu_vx", 5 },
  { "vmslt_vv", 2 },
  { "vmslt_vx", 5 },
  { "vmsleu_vi", 4 },
  { "vmsleu_vv", 2 },
  { "vmsleu_vx", 5 },
  { "vmsle_vi", 4 },
  { "vmsle_vv", 2 },
  { "vmsle_vx", 5 },
  { "vmsgtu_vi", 4 },
  { "vmsgtu_vx", 5 },
  { "vmsgt_vi", 4 },
  { "vmsgt_vx", 5 },
  { "vminu_vv", 2 },
  { "vminu_vx", 5 },
  { "vmin_vv", 2 },
  { "vmin_vx", 5 },
  { "vmaxu_vv", 2 },
  { "vmaxu_vx", 5 },
  { "vmax_vv", 2 },
  { "vmax_vx", 5 },
  { "vmerge_vim", 2 },
  { "vmerge_vvm", 1 },
  { "vmerge_vxm", 3 },
  { "vmv_v_i", 1 },
  { "vmv_v_v", 1 },
  { "vmv_v_x", 1 },
  { "vzext_vf2", 1 },
  { "vzext_vf4", 1 },
  { "vsext_vf2", 1 },
  { "vsext_vf4", 1 },
  -- #40 vector memory: unit-stride widths, fault-only-first, strided,
  -- indexed, mask, whole-register, and segment forms
  { "vl1re16_v", 1 },
  { "vl1re32_v", 1 },
  { "vl1re8_v", 1 },
  { "vl2re16_v", 1 },
  { "vl2re32_v", 1 },
  { "vl2re8_v", 1 },
  { "vl4re16_v", 1 },
  { "vl4re32_v", 1 },
  { "vl4re8_v", 1 },
  { "vl8re16_v", 1 },
  { "vl8re32_v", 1 },
  { "vl8re8_v", 1 },
  { "vle16_v", 1 },
  { "vle16ff_v", 1 },
  { "vle32_v", 1 },
  { "vle32ff_v", 1 },
  { "vle8_v", 1 },
  { "vle8ff_v", 1 },
  { "vlm_v", 1 },
  { "vloxei16_v", 2 },
  { "vloxei32_v", 1 },
  { "vloxei8_v", 2 },
  { "vloxseg2ei16_v", 2 },
  { "vloxseg2ei32_v", 1 },
  { "vloxseg2ei8_v", 2 },
  { "vloxseg3ei16_v", 2 },
  { "vloxseg3ei32_v", 1 },
  { "vloxseg3ei8_v", 2 },
  { "vloxseg4ei16_v", 2 },
  { "vloxseg4ei32_v", 1 },
  { "vloxseg4ei8_v", 2 },
  { "vloxseg5ei16_v", 1 },
  { "vloxseg5ei32_v", 1 },
  { "vloxseg5ei8_v", 1 },
  { "vloxseg6ei16_v", 1 },
  { "vloxseg6ei32_v", 1 },
  { "vloxseg6ei8_v", 2 },
  { "vloxseg7ei16_v", 2 },
  { "vloxseg7ei32_v", 1 },
  { "vloxseg7ei8_v", 2 },
  { "vloxseg8ei16_v", 2 },
  { "vloxseg8ei32_v", 1 },
  { "vloxseg8ei8_v", 2 },
  { "vlse16_v", 2 },
  { "vlse32_v", 2 },
  { "vlse8_v", 2 },
  { "vlseg2e16_v", 1 },
  { "vlseg2e16ff_v", 1 },
  { "vlseg2e32_v", 1 },
  { "vlseg2e32ff_v", 1 },
  { "vlseg2e8_v", 1 },
  { "vlseg2e8ff_v", 1 },
  { "vlseg3e16_v", 1 },
  { "vlseg3e16ff_v", 1 },
  { "vlseg3e32_v", 1 },
  { "vlseg3e32ff_v", 1 },
  { "vlseg3e8_v", 1 },
  { "vlseg3e8ff_v", 1 },
  { "vlseg4e16_v", 1 },
  { "vlseg4e16ff_v", 1 },
  { "vlseg4e32_v", 1 },
  { "vlseg4e32ff_v", 1 },
  { "vlseg4e8_v", 1 },
  { "vlseg4e8ff_v", 1 },
  { "vlseg5e16_v", 1 },
  { "vlseg5e16ff_v", 1 },
  { "vlseg5e32_v", 1 },
  { "vlseg5e32ff_v", 1 },
  { "vlseg5e8_v", 1 },
  { "vlseg5e8ff_v", 1 },
  { "vlseg6e16_v", 1 },
  { "vlseg6e16ff_v", 1 },
  { "vlseg6e32_v", 1 },
  { "vlseg6e32ff_v", 1 },
  { "vlseg6e8_v", 1 },
  { "vlseg6e8ff_v", 1 },
  { "vlseg7e16_v", 1 },
  { "vlseg7e16ff_v", 1 },
  { "vlseg7e32_v", 1 },
  { "vlseg7e32ff_v", 1 },
  { "vlseg7e8_v", 1 },
  { "vlseg7e8ff_v", 1 },
  { "vlseg8e16_v", 1 },
  { "vlseg8e16ff_v", 1 },
  { "vlseg8e32_v", 1 },
  { "vlseg8e32ff_v", 1 },
  { "vlseg8e8_v", 1 },
  { "vlseg8e8ff_v", 1 },
  { "vlsseg2e16_v", 2 },
  { "vlsseg2e32_v", 2 },
  { "vlsseg2e8_v", 2 },
  { "vlsseg3e16_v", 2 },
  { "vlsseg3e32_v", 1 },
  { "vlsseg3e8_v", 2 },
  { "vlsseg4e16_v", 2 },
  { "vlsseg4e32_v", 2 },
  { "vlsseg4e8_v", 3 },
  { "vlsseg5e16_v", 2 },
  { "vlsseg5e32_v", 1 },
  { "vlsseg5e8_v", 2 },
  { "vlsseg6e16_v", 2 },
  { "vlsseg6e32_v", 1 },
  { "vlsseg6e8_v", 3 },
  { "vlsseg7e16_v", 2 },
  { "vlsseg7e32_v", 1 },
  { "vlsseg7e8_v", 3 },
  { "vlsseg8e16_v", 2 },
  { "vlsseg8e32_v", 1 },
  { "vlsseg8e8_v", 3 },
  { "vluxei16_v", 2 },
  { "vluxei32_v", 1 },
  { "vluxei8_v", 2 },
  { "vluxseg2ei16_v", 2 },
  { "vluxseg2ei32_v", 1 },
  { "vluxseg2ei8_v", 2 },
  { "vluxseg3ei16_v", 2 },
  { "vluxseg3ei32_v", 1 },
  { "vluxseg3ei8_v", 2 },
  { "vluxseg4ei16_v", 2 },
  { "vluxseg4ei32_v", 1 },
  { "vluxseg4ei8_v", 2 },
  { "vluxseg5ei16_v", 1 },
  { "vluxseg5ei32_v", 1 },
  { "vluxseg5ei8_v", 1 },
  { "vluxseg6ei16_v", 1 },
  { "vluxseg6ei32_v", 1 },
  { "vluxseg6ei8_v", 2 },
  { "vluxseg7ei16_v", 2 },
  { "vluxseg7ei32_v", 1 },
  { "vluxseg7ei8_v", 2 },
  { "vluxseg8ei16_v", 2 },
  { "vluxseg8ei32_v", 1 },
  { "vluxseg8ei8_v", 2 },
  { "vs1r_v", 1 },
  { "vs2r_v", 1 },
  { "vs4r_v", 1 },
  { "vs8r_v", 1 },
  { "vse16_v", 1 },
  { "vse32_v", 1 },
  { "vse8_v", 1 },
  { "vsm_v", 1 },
  { "vsoxei16_v", 2 },
  { "vsoxei32_v", 1 },
  { "vsoxei8_v", 2 },
  { "vsoxseg2ei16_v", 2 },
  { "vsoxseg2ei32_v", 1 },
  { "vsoxseg2ei8_v", 2 },
  { "vsoxseg3ei16_v", 1 },
  { "vsoxseg3ei32_v", 1 },
  { "vsoxseg3ei8_v", 1 },
  { "vsoxseg4ei16_v", 1 },
  { "vsoxseg4ei32_v", 1 },
  { "vsoxseg4ei8_v", 2 },
  { "vsoxseg5ei16_v", 1 },
  { "vsoxseg5ei32_v", 1 },
  { "vsoxseg5ei8_v", 1 },
  { "vsoxseg6ei16_v", 1 },
  { "vsoxseg6ei32_v", 1 },
  { "vsoxseg6ei8_v", 1 },
  { "vsoxseg7ei16_v", 1 },
  { "vsoxseg7ei32_v", 1 },
  { "vsoxseg7ei8_v", 1 },
  { "vsoxseg8ei16_v", 1 },
  { "vsoxseg8ei32_v", 1 },
  { "vsoxseg8ei8_v", 2 },
  { "vsse16_v", 1 },
  { "vsse32_v", 1 },
  { "vsse8_v", 2 },
  { "vsseg2e16_v", 1 },
  { "vsseg2e32_v", 1 },
  { "vsseg2e8_v", 1 },
  { "vsseg3e16_v", 1 },
  { "vsseg3e32_v", 1 },
  { "vsseg3e8_v", 1 },
  { "vsseg4e16_v", 1 },
  { "vsseg4e32_v", 1 },
  { "vsseg4e8_v", 1 },
  { "vsseg5e16_v", 1 },
  { "vsseg5e32_v", 1 },
  { "vsseg5e8_v", 1 },
  { "vsseg6e16_v", 1 },
  { "vsseg6e32_v", 1 },
  { "vsseg6e8_v", 1 },
  { "vsseg7e16_v", 1 },
  { "vsseg7e32_v", 1 },
  { "vsseg7e8_v", 1 },
  { "vsseg8e16_v", 1 },
  { "vsseg8e32_v", 1 },
  { "vsseg8e8_v", 1 },
  { "vssseg2e16_v", 2 },
  { "vssseg2e32_v", 1 },
  { "vssseg2e8_v", 2 },
  { "vssseg3e16_v", 2 },
  { "vssseg3e32_v", 1 },
  { "vssseg3e8_v", 2 },
  { "vssseg4e16_v", 2 },
  { "vssseg4e32_v", 1 },
  { "vssseg4e8_v", 2 },
  { "vssseg5e16_v", 2 },
  { "vssseg5e32_v", 1 },
  { "vssseg5e8_v", 2 },
  { "vssseg6e16_v", 2 },
  { "vssseg6e32_v", 1 },
  { "vssseg6e8_v", 3 },
  { "vssseg7e16_v", 2 },
  { "vssseg7e32_v", 1 },
  { "vssseg7e8_v", 3 },
  { "vssseg8e16_v", 2 },
  { "vssseg8e32_v", 1 },
  { "vssseg8e8_v", 3 },
  { "vsuxei16_v", 2 },
  { "vsuxei32_v", 1 },
  { "vsuxei8_v", 2 },
  { "vsuxseg2ei16_v", 2 },
  { "vsuxseg2ei32_v", 1 },
  { "vsuxseg2ei8_v", 2 },
  { "vsuxseg3ei16_v", 1 },
  { "vsuxseg3ei32_v", 1 },
  { "vsuxseg3ei8_v", 1 },
  { "vsuxseg4ei16_v", 1 },
  { "vsuxseg4ei32_v", 1 },
  { "vsuxseg4ei8_v", 2 },
  { "vsuxseg5ei16_v", 1 },
  { "vsuxseg5ei32_v", 1 },
  { "vsuxseg5ei8_v", 1 },
  { "vsuxseg6ei16_v", 1 },
  { "vsuxseg6ei32_v", 1 },
  { "vsuxseg6ei8_v", 1 },
  { "vsuxseg7ei16_v", 1 },
  { "vsuxseg7ei32_v", 1 },
  { "vsuxseg7ei8_v", 1 },
  { "vsuxseg8ei16_v", 1 },
  { "vsuxseg8ei32_v", 1 },
  { "vsuxseg8ei8_v", 2 },
  -- #43 reductions: single-width integer + widening sums
  { "vredand_vs", 2 },
  { "vredmax_vs", 2 },
  { "vredmaxu_vs", 2 },
  { "vredmin_vs", 2 },
  { "vredminu_vs", 2 },
  { "vredor_vs", 2 },
  { "vredsum_vs", 2 },
  { "vredxor_vs", 2 },
  { "vwredsum_vs", 2 },
  { "vwredsumu_vs", 2 },
  -- #43 mask instructions: logicals, population count, find-first-set
  { "vmand_mm", 1 },
  { "vmandn_mm", 1 },
  { "vmnand_mm", 1 },
  { "vmnor_mm", 1 },
  { "vmor_mm", 1 },
  { "vmorn_mm", 1 },
  { "vmxnor_mm", 1 },
  { "vmxor_mm", 1 },
  { "vcpop_m", 1 },
  { "vfirst_m", 1 },
  -- #43 mask instructions: set-before/including/only-first, iota, index
  { "vmsbf_m", 1 },
  { "vmsif_m", 1 },
  { "vmsof_m", 1 },
  { "viota_m", 2 },
  { "vid_v", 1 },
}
local VALLOW = {}
for _, fam in ipairs(VFAMILIES) do
  for i = 0, fam[2] - 1 do
    VALLOW[#VALLOW + 1] = fam[1] .. "-" .. i
  end
end

local function read(path)
  local f = assert(io.open(path, "r"), "missing fixture: " .. path)
  local s = f:read("*a")
  f:close()
  return s
end

local function conformance(dir, name, max_steps)
  local image = asm.assemble(read(dir .. name .. ".s"))
  local hart = Hart.new(Mem.new())
  hart:load(image)
  local r = hart:run({ max_steps = max_steps })
  assert.is_truthy(r.tohost, "no tohost write within step budget (hung?)")
  local testnum = math.floor((r.tohost or 0) / 2)
  assert.are.equal(1, r.tohost, "failed at test #" .. testnum)
end

describe("riscv-tests conformance", function()
  for _, name in ipairs(ALLOW) do
    it(name .. " passes", function()
      conformance(FIXTURES, name, 200000)
    end)
  end
end)

describe("riscv-vector-tests conformance", function()
  for _, name in ipairs(VALLOW) do
    it(name .. " passes", function()
      conformance(VFIXTURES, name, 2000000)
    end)
  end
end)
