# This file is automatically generated. Do not edit.
# Instruction: vl1re8.v
#-----------------------------------------------------------------------
# Helper macros
#-----------------------------------------------------------------------
# We use a macro hack to simpify code generation for various numbers
# of bubble cycles.
#-----------------------------------------------------------------------
# RV64UI MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for instructions with immediate operand
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register-register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test memory instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test jump instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# RV64UF MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests floating-point instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Pass and fail code (assumes test num is in gp)
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test data section
#-----------------------------------------------------------------------
.macro init; li t5, (0x00000600 & (0x00000600 >> 1)); csrs mstatus, t5; csrwi vcsr, 0;; .endm
.section .text.init; .align 6; .weak mtvec_handler; .globl _start; _start: j reset_vector; .align 2; trap_vector: csrr t5, mcause; li t6, 0xb; beq t5, t6, write_tohost; li t6, 0x8; beq t5, t6, write_tohost; li t6, 0x9; beq t5, t6, write_tohost; la t5, mtvec_handler; beqz t5, 1f; jr t5; 1: ori gp, gp, 1337; write_tohost: sw gp, tohost, t5; sw zero, tohost + 4, t5; j write_tohost; reset_vector: li gp, 0; la t0, trap_vector; csrw mtvec, t0; init;
 # Zero all vector registers
vsetvli t0, x0, e8,m8,tu,mu
vmv.v.i v0, 0x0
vmv.v.i v8, 0x0
vmv.v.i v16, 0x0
vmv.v.i v24, 0x0
# Generating tests for VL: 0, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 0
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 16
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_2: li gp, 2; lw t0, 0(a0); addi a0, a0, 4; la x7, test_2_data; lw x7, 0(x7); beq t0, x7, test_2_success; la x7, fail; jr x7; .align 3; test_2_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_2_success:
  test_3: li gp, 3; lw t0, 0(a0); addi a0, a0, 4; la x7, test_3_data; lw x7, 0(x7); beq t0, x7, test_3_success; la x7, fail; jr x7; .align 3; test_3_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_3_success:
  test_4: li gp, 4; lw t0, 0(a0); addi a0, a0, 4; la x7, test_4_data; lw x7, 0(x7); beq t0, x7, test_4_success; la x7, fail; jr x7; .align 3; test_4_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_4_success:
  test_5: li gp, 5; lw t0, 0(a0); addi a0, a0, 4; la x7, test_5_data; lw x7, 0(x7); beq t0, x7, test_5_success; la x7, fail; jr x7; .align 3; test_5_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_5_success:
 # Generating tests for VL: 7, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 32
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 48
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 7
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_6: li gp, 6; lw t0, 0(a0); addi a0, a0, 4; la x7, test_6_data; lw x7, 0(x7); beq t0, x7, test_6_success; la x7, fail; jr x7; .align 3; test_6_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_6_success:
  test_7: li gp, 7; lw t0, 0(a0); addi a0, a0, 4; la x7, test_7_data; lw x7, 0(x7); beq t0, x7, test_7_success; la x7, fail; jr x7; .align 3; test_7_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_7_success:
  test_8: li gp, 8; lw t0, 0(a0); addi a0, a0, 4; la x7, test_8_data; lw x7, 0(x7); beq t0, x7, test_8_success; la x7, fail; jr x7; .align 3; test_8_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_8_success:
  test_9: li gp, 9; lw t0, 0(a0); addi a0, a0, 4; la x7, test_9_data; lw x7, 0(x7); beq t0, x7, test_9_success; la x7, fail; jr x7; .align 3; test_9_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_9_success:
 # Generating tests for VL: 8, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 64
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 80
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 8
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_10: li gp, 10; lw t0, 0(a0); addi a0, a0, 4; la x7, test_10_data; lw x7, 0(x7); beq t0, x7, test_10_success; la x7, fail; jr x7; .align 3; test_10_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_10_success:
  test_11: li gp, 11; lw t0, 0(a0); addi a0, a0, 4; la x7, test_11_data; lw x7, 0(x7); beq t0, x7, test_11_success; la x7, fail; jr x7; .align 3; test_11_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_11_success:
  test_12: li gp, 12; lw t0, 0(a0); addi a0, a0, 4; la x7, test_12_data; lw x7, 0(x7); beq t0, x7, test_12_success; la x7, fail; jr x7; .align 3; test_12_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_12_success:
  test_13: li gp, 13; lw t0, 0(a0); addi a0, a0, 4; la x7, test_13_data; lw x7, 0(x7); beq t0, x7, test_13_success; la x7, fail; jr x7; .align 3; test_13_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_13_success:
 # Generating tests for VL: 16, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 96
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 112
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 16
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_14: li gp, 14; lw t0, 0(a0); addi a0, a0, 4; la x7, test_14_data; lw x7, 0(x7); beq t0, x7, test_14_success; la x7, fail; jr x7; .align 3; test_14_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_14_success:
  test_15: li gp, 15; lw t0, 0(a0); addi a0, a0, 4; la x7, test_15_data; lw x7, 0(x7); beq t0, x7, test_15_success; la x7, fail; jr x7; .align 3; test_15_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_15_success:
  test_16: li gp, 16; lw t0, 0(a0); addi a0, a0, 4; la x7, test_16_data; lw x7, 0(x7); beq t0, x7, test_16_success; la x7, fail; jr x7; .align 3; test_16_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_16_success:
  test_17: li gp, 17; lw t0, 0(a0); addi a0, a0, 4; la x7, test_17_data; lw x7, 0(x7); beq t0, x7, test_17_success; la x7, fail; jr x7; .align 3; test_17_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_17_success:
 # Generating tests for VL: 15, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 128
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 144
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 15
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_18: li gp, 18; lw t0, 0(a0); addi a0, a0, 4; la x7, test_18_data; lw x7, 0(x7); beq t0, x7, test_18_success; la x7, fail; jr x7; .align 3; test_18_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_18_success:
  test_19: li gp, 19; lw t0, 0(a0); addi a0, a0, 4; la x7, test_19_data; lw x7, 0(x7); beq t0, x7, test_19_success; la x7, fail; jr x7; .align 3; test_19_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_19_success:
  test_20: li gp, 20; lw t0, 0(a0); addi a0, a0, 4; la x7, test_20_data; lw x7, 0(x7); beq t0, x7, test_20_success; la x7, fail; jr x7; .align 3; test_20_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_20_success:
  test_21: li gp, 21; lw t0, 0(a0); addi a0, a0, 4; la x7, test_21_data; lw x7, 0(x7); beq t0, x7, test_21_success; la x7, fail; jr x7; .align 3; test_21_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_21_success:
 # Generating tests for VL: 17, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 160
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 176
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 17
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_22: li gp, 22; lw t0, 0(a0); addi a0, a0, 4; la x7, test_22_data; lw x7, 0(x7); beq t0, x7, test_22_success; la x7, fail; jr x7; .align 3; test_22_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_22_success:
  test_23: li gp, 23; lw t0, 0(a0); addi a0, a0, 4; la x7, test_23_data; lw x7, 0(x7); beq t0, x7, test_23_success; la x7, fail; jr x7; .align 3; test_23_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_23_success:
  test_24: li gp, 24; lw t0, 0(a0); addi a0, a0, 4; la x7, test_24_data; lw x7, 0(x7); beq t0, x7, test_24_success; la x7, fail; jr x7; .align 3; test_24_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_24_success:
  test_25: li gp, 25; lw t0, 0(a0); addi a0, a0, 4; la x7, test_25_data; lw x7, 0(x7); beq t0, x7, test_25_success; la x7, fail; jr x7; .align 3; test_25_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_25_success:
 # Generating tests for VL: 12, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 192
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 208
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_26: li gp, 26; lw t0, 0(a0); addi a0, a0, 4; la x7, test_26_data; lw x7, 0(x7); beq t0, x7, test_26_success; la x7, fail; jr x7; .align 3; test_26_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_26_success:
  test_27: li gp, 27; lw t0, 0(a0); addi a0, a0, 4; la x7, test_27_data; lw x7, 0(x7); beq t0, x7, test_27_success; la x7, fail; jr x7; .align 3; test_27_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_27_success:
  test_28: li gp, 28; lw t0, 0(a0); addi a0, a0, 4; la x7, test_28_data; lw x7, 0(x7); beq t0, x7, test_28_success; la x7, fail; jr x7; .align 3; test_28_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_28_success:
  test_29: li gp, 29; lw t0, 0(a0); addi a0, a0, 4; la x7, test_29_data; lw x7, 0(x7); beq t0, x7, test_29_success; la x7, fail; jr x7; .align 3; test_29_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_29_success:
 # Generating tests for VL: 12, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 224
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 240
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_30: li gp, 30; lw t0, 0(a0); addi a0, a0, 4; la x7, test_30_data; lw x7, 0(x7); beq t0, x7, test_30_success; la x7, fail; jr x7; .align 3; test_30_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_30_success:
  test_31: li gp, 31; lw t0, 0(a0); addi a0, a0, 4; la x7, test_31_data; lw x7, 0(x7); beq t0, x7, test_31_success; la x7, fail; jr x7; .align 3; test_31_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_31_success:
  test_32: li gp, 32; lw t0, 0(a0); addi a0, a0, 4; la x7, test_32_data; lw x7, 0(x7); beq t0, x7, test_32_success; la x7, fail; jr x7; .align 3; test_32_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_32_success:
  test_33: li gp, 33; lw t0, 0(a0); addi a0, a0, 4; la x7, test_33_data; lw x7, 0(x7); beq t0, x7, test_33_success; la x7, fail; jr x7; .align 3; test_33_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_33_success:
 # Generating tests for VL: 12, LMUL: m1, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 256
add a0, a0, a5
# Load data into v22 register group.
vsetvli t1, x0, e8,m1,tu,mu
vle8.v v22, (a0)
# Move a0 to test data area.
la a0, testdata
li a5, 272
add a0, a0, a5
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e8,m1,tu,mu
vl1re8.v v22, (a0)
# -------------- TEST END --------------
la a0, resultdata
# Store v22 register group into result data area.
vsetvli t1, x0, e8,m1,tu,mu
vse8.v v22, (a0)
  test_34: li gp, 34; lw t0, 0(a0); addi a0, a0, 4; la x7, test_34_data; lw x7, 0(x7); beq t0, x7, test_34_success; la x7, fail; jr x7; .align 3; test_34_data: .quad ((0xf020100) & ((1 << (32 - 1) << 1) - 1)); test_34_success:
  test_35: li gp, 35; lw t0, 0(a0); addi a0, a0, 4; la x7, test_35_data; lw x7, 0(x7); beq t0, x7, test_35_success; la x7, fail; jr x7; .align 3; test_35_data: .quad ((0xfff87f) & ((1 << (32 - 1) << 1) - 1)); test_35_success:
  test_36: li gp, 36; lw t0, 0(a0); addi a0, a0, 4; la x7, test_36_data; lw x7, 0(x7); beq t0, x7, test_36_success; la x7, fail; jr x7; .align 3; test_36_data: .quad ((0x7f0f0201) & ((1 << (32 - 1) << 1) - 1)); test_36_success:
  test_37: li gp, 37; lw t0, 0(a0); addi a0, a0, 4; la x7, test_37_data; lw x7, 0(x7); beq t0, x7, test_37_success; la x7, fail; jr x7; .align 3; test_37_data: .quad ((0x100fff8) & ((1 << (32 - 1) << 1) - 1)); test_37_success:
  bne x0, gp, pass; fail: fence; 1: beqz gp, 1b; sll gp, gp, 1; or gp, gp, 1; ecall; pass: fence; li gp, 1; ecall
unimp
  .data
.pushsection .tohost, "aw", @progbits; .align 6; .global tohost; tohost: .dword 0; .align 6; .global fromhost; fromhost: .dword 0; .popsection; .align 4; .global begin_signature; begin_signature:
 # Reserve space for test data.
resultdata:
  .zero 1024
testdata:
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
  .quad 0x30ac75dc32808aa4
  .quad 0x8344c0aa5b761295
  .quad 0xfff87f0f020100
  .quad 0x100fff87f0f0201
.align 4; .global end_signature; end_signature:
