# This file is automatically generated. Do not edit.
# Instruction: vmv2r.v
#-----------------------------------------------------------------------
# Helper macros
#-----------------------------------------------------------------------
# We use a macro hack to simpify code generation for various numbers
# of bubble cycles.
#-----------------------------------------------------------------------
# RV64UI MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for instructions with immediate operand
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register-register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test memory instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test jump instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# RV64UF MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests floating-point instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Pass and fail code (assumes test num is in gp)
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test data section
#-----------------------------------------------------------------------
.macro init; li t5, (0x00000600 & (0x00000600 >> 1)); csrs mstatus, t5; csrwi vcsr, 0;; .endm
.section .text.init; .align 6; .weak mtvec_handler; .globl _start; _start: j reset_vector; .align 2; trap_vector: csrr t5, mcause; li t6, 0xb; beq t5, t6, write_tohost; li t6, 0x8; beq t5, t6, write_tohost; li t6, 0x9; beq t5, t6, write_tohost; la t5, mtvec_handler; beqz t5, 1f; jr t5; 1: ori gp, gp, 1337; write_tohost: sw gp, tohost, t5; sw zero, tohost + 4, t5; j write_tohost; reset_vector: li gp, 0; la t0, trap_vector; csrw mtvec, t0; init;
 # Zero all vector registers
vsetvli t0, x0, e8,m8,tu,mu
vmv.v.i v0, 0x0
vmv.v.i v8, 0x0
vmv.v.i v16, 0x0
vmv.v.i v24, 0x0
# Generating tests for VL: 0, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 0
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_2: li gp, 2; lw t0, 0(a0); addi a0, a0, 4; la x7, test_2_data; lw x7, 0(x7); beq t0, x7, test_2_success; la x7, fail; jr x7; .align 3; test_2_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_2_success:
  test_3: li gp, 3; lw t0, 0(a0); addi a0, a0, 4; la x7, test_3_data; lw x7, 0(x7); beq t0, x7, test_3_success; la x7, fail; jr x7; .align 3; test_3_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_3_success:
  test_4: li gp, 4; lw t0, 0(a0); addi a0, a0, 4; la x7, test_4_data; lw x7, 0(x7); beq t0, x7, test_4_success; la x7, fail; jr x7; .align 3; test_4_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_4_success:
  test_5: li gp, 5; lw t0, 0(a0); addi a0, a0, 4; la x7, test_5_data; lw x7, 0(x7); beq t0, x7, test_5_success; la x7, fail; jr x7; .align 3; test_5_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_5_success:
  test_6: li gp, 6; lw t0, 0(a0); addi a0, a0, 4; la x7, test_6_data; lw x7, 0(x7); beq t0, x7, test_6_success; la x7, fail; jr x7; .align 3; test_6_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_6_success:
  test_7: li gp, 7; lw t0, 0(a0); addi a0, a0, 4; la x7, test_7_data; lw x7, 0(x7); beq t0, x7, test_7_success; la x7, fail; jr x7; .align 3; test_7_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_7_success:
  test_8: li gp, 8; lw t0, 0(a0); addi a0, a0, 4; la x7, test_8_data; lw x7, 0(x7); beq t0, x7, test_8_success; la x7, fail; jr x7; .align 3; test_8_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_8_success:
  test_9: li gp, 9; lw t0, 0(a0); addi a0, a0, 4; la x7, test_9_data; lw x7, 0(x7); beq t0, x7, test_9_success; la x7, fail; jr x7; .align 3; test_9_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_9_success:
 # Generating tests for VL: 15, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 64
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 15
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_10: li gp, 10; lw t0, 0(a0); addi a0, a0, 4; la x7, test_10_data; lw x7, 0(x7); beq t0, x7, test_10_success; la x7, fail; jr x7; .align 3; test_10_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_10_success:
  test_11: li gp, 11; lw t0, 0(a0); addi a0, a0, 4; la x7, test_11_data; lw x7, 0(x7); beq t0, x7, test_11_success; la x7, fail; jr x7; .align 3; test_11_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_11_success:
  test_12: li gp, 12; lw t0, 0(a0); addi a0, a0, 4; la x7, test_12_data; lw x7, 0(x7); beq t0, x7, test_12_success; la x7, fail; jr x7; .align 3; test_12_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_12_success:
  test_13: li gp, 13; lw t0, 0(a0); addi a0, a0, 4; la x7, test_13_data; lw x7, 0(x7); beq t0, x7, test_13_success; la x7, fail; jr x7; .align 3; test_13_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_13_success:
  test_14: li gp, 14; lw t0, 0(a0); addi a0, a0, 4; la x7, test_14_data; lw x7, 0(x7); beq t0, x7, test_14_success; la x7, fail; jr x7; .align 3; test_14_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_14_success:
  test_15: li gp, 15; lw t0, 0(a0); addi a0, a0, 4; la x7, test_15_data; lw x7, 0(x7); beq t0, x7, test_15_success; la x7, fail; jr x7; .align 3; test_15_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_15_success:
  test_16: li gp, 16; lw t0, 0(a0); addi a0, a0, 4; la x7, test_16_data; lw x7, 0(x7); beq t0, x7, test_16_success; la x7, fail; jr x7; .align 3; test_16_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_16_success:
  test_17: li gp, 17; lw t0, 0(a0); addi a0, a0, 4; la x7, test_17_data; lw x7, 0(x7); beq t0, x7, test_17_success; la x7, fail; jr x7; .align 3; test_17_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_17_success:
 # Generating tests for VL: 16, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 128
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 16
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_18: li gp, 18; lw t0, 0(a0); addi a0, a0, 4; la x7, test_18_data; lw x7, 0(x7); beq t0, x7, test_18_success; la x7, fail; jr x7; .align 3; test_18_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_18_success:
  test_19: li gp, 19; lw t0, 0(a0); addi a0, a0, 4; la x7, test_19_data; lw x7, 0(x7); beq t0, x7, test_19_success; la x7, fail; jr x7; .align 3; test_19_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_19_success:
  test_20: li gp, 20; lw t0, 0(a0); addi a0, a0, 4; la x7, test_20_data; lw x7, 0(x7); beq t0, x7, test_20_success; la x7, fail; jr x7; .align 3; test_20_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_20_success:
  test_21: li gp, 21; lw t0, 0(a0); addi a0, a0, 4; la x7, test_21_data; lw x7, 0(x7); beq t0, x7, test_21_success; la x7, fail; jr x7; .align 3; test_21_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_21_success:
  test_22: li gp, 22; lw t0, 0(a0); addi a0, a0, 4; la x7, test_22_data; lw x7, 0(x7); beq t0, x7, test_22_success; la x7, fail; jr x7; .align 3; test_22_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_22_success:
  test_23: li gp, 23; lw t0, 0(a0); addi a0, a0, 4; la x7, test_23_data; lw x7, 0(x7); beq t0, x7, test_23_success; la x7, fail; jr x7; .align 3; test_23_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_23_success:
  test_24: li gp, 24; lw t0, 0(a0); addi a0, a0, 4; la x7, test_24_data; lw x7, 0(x7); beq t0, x7, test_24_success; la x7, fail; jr x7; .align 3; test_24_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_24_success:
  test_25: li gp, 25; lw t0, 0(a0); addi a0, a0, 4; la x7, test_25_data; lw x7, 0(x7); beq t0, x7, test_25_success; la x7, fail; jr x7; .align 3; test_25_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_25_success:
 # Generating tests for VL: 32, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 192
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 32
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_26: li gp, 26; lw t0, 0(a0); addi a0, a0, 4; la x7, test_26_data; lw x7, 0(x7); beq t0, x7, test_26_success; la x7, fail; jr x7; .align 3; test_26_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_26_success:
  test_27: li gp, 27; lw t0, 0(a0); addi a0, a0, 4; la x7, test_27_data; lw x7, 0(x7); beq t0, x7, test_27_success; la x7, fail; jr x7; .align 3; test_27_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_27_success:
  test_28: li gp, 28; lw t0, 0(a0); addi a0, a0, 4; la x7, test_28_data; lw x7, 0(x7); beq t0, x7, test_28_success; la x7, fail; jr x7; .align 3; test_28_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_28_success:
  test_29: li gp, 29; lw t0, 0(a0); addi a0, a0, 4; la x7, test_29_data; lw x7, 0(x7); beq t0, x7, test_29_success; la x7, fail; jr x7; .align 3; test_29_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_29_success:
  test_30: li gp, 30; lw t0, 0(a0); addi a0, a0, 4; la x7, test_30_data; lw x7, 0(x7); beq t0, x7, test_30_success; la x7, fail; jr x7; .align 3; test_30_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_30_success:
  test_31: li gp, 31; lw t0, 0(a0); addi a0, a0, 4; la x7, test_31_data; lw x7, 0(x7); beq t0, x7, test_31_success; la x7, fail; jr x7; .align 3; test_31_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_31_success:
  test_32: li gp, 32; lw t0, 0(a0); addi a0, a0, 4; la x7, test_32_data; lw x7, 0(x7); beq t0, x7, test_32_success; la x7, fail; jr x7; .align 3; test_32_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_32_success:
  test_33: li gp, 33; lw t0, 0(a0); addi a0, a0, 4; la x7, test_33_data; lw x7, 0(x7); beq t0, x7, test_33_success; la x7, fail; jr x7; .align 3; test_33_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_33_success:
 # Generating tests for VL: 31, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 256
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 31
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_34: li gp, 34; lw t0, 0(a0); addi a0, a0, 4; la x7, test_34_data; lw x7, 0(x7); beq t0, x7, test_34_success; la x7, fail; jr x7; .align 3; test_34_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_34_success:
  test_35: li gp, 35; lw t0, 0(a0); addi a0, a0, 4; la x7, test_35_data; lw x7, 0(x7); beq t0, x7, test_35_success; la x7, fail; jr x7; .align 3; test_35_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_35_success:
  test_36: li gp, 36; lw t0, 0(a0); addi a0, a0, 4; la x7, test_36_data; lw x7, 0(x7); beq t0, x7, test_36_success; la x7, fail; jr x7; .align 3; test_36_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_36_success:
  test_37: li gp, 37; lw t0, 0(a0); addi a0, a0, 4; la x7, test_37_data; lw x7, 0(x7); beq t0, x7, test_37_success; la x7, fail; jr x7; .align 3; test_37_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_37_success:
  test_38: li gp, 38; lw t0, 0(a0); addi a0, a0, 4; la x7, test_38_data; lw x7, 0(x7); beq t0, x7, test_38_success; la x7, fail; jr x7; .align 3; test_38_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_38_success:
  test_39: li gp, 39; lw t0, 0(a0); addi a0, a0, 4; la x7, test_39_data; lw x7, 0(x7); beq t0, x7, test_39_success; la x7, fail; jr x7; .align 3; test_39_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_39_success:
  test_40: li gp, 40; lw t0, 0(a0); addi a0, a0, 4; la x7, test_40_data; lw x7, 0(x7); beq t0, x7, test_40_success; la x7, fail; jr x7; .align 3; test_40_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_40_success:
  test_41: li gp, 41; lw t0, 0(a0); addi a0, a0, 4; la x7, test_41_data; lw x7, 0(x7); beq t0, x7, test_41_success; la x7, fail; jr x7; .align 3; test_41_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_41_success:
 # Generating tests for VL: 33, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 320
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 33
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_42: li gp, 42; lw t0, 0(a0); addi a0, a0, 4; la x7, test_42_data; lw x7, 0(x7); beq t0, x7, test_42_success; la x7, fail; jr x7; .align 3; test_42_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_42_success:
  test_43: li gp, 43; lw t0, 0(a0); addi a0, a0, 4; la x7, test_43_data; lw x7, 0(x7); beq t0, x7, test_43_success; la x7, fail; jr x7; .align 3; test_43_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_43_success:
  test_44: li gp, 44; lw t0, 0(a0); addi a0, a0, 4; la x7, test_44_data; lw x7, 0(x7); beq t0, x7, test_44_success; la x7, fail; jr x7; .align 3; test_44_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_44_success:
  test_45: li gp, 45; lw t0, 0(a0); addi a0, a0, 4; la x7, test_45_data; lw x7, 0(x7); beq t0, x7, test_45_success; la x7, fail; jr x7; .align 3; test_45_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_45_success:
  test_46: li gp, 46; lw t0, 0(a0); addi a0, a0, 4; la x7, test_46_data; lw x7, 0(x7); beq t0, x7, test_46_success; la x7, fail; jr x7; .align 3; test_46_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_46_success:
  test_47: li gp, 47; lw t0, 0(a0); addi a0, a0, 4; la x7, test_47_data; lw x7, 0(x7); beq t0, x7, test_47_success; la x7, fail; jr x7; .align 3; test_47_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_47_success:
  test_48: li gp, 48; lw t0, 0(a0); addi a0, a0, 4; la x7, test_48_data; lw x7, 0(x7); beq t0, x7, test_48_success; la x7, fail; jr x7; .align 3; test_48_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_48_success:
  test_49: li gp, 49; lw t0, 0(a0); addi a0, a0, 4; la x7, test_49_data; lw x7, 0(x7); beq t0, x7, test_49_success; la x7, fail; jr x7; .align 3; test_49_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_49_success:
 # Generating tests for VL: 2, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 384
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 2
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_50: li gp, 50; lw t0, 0(a0); addi a0, a0, 4; la x7, test_50_data; lw x7, 0(x7); beq t0, x7, test_50_success; la x7, fail; jr x7; .align 3; test_50_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_50_success:
  test_51: li gp, 51; lw t0, 0(a0); addi a0, a0, 4; la x7, test_51_data; lw x7, 0(x7); beq t0, x7, test_51_success; la x7, fail; jr x7; .align 3; test_51_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_51_success:
  test_52: li gp, 52; lw t0, 0(a0); addi a0, a0, 4; la x7, test_52_data; lw x7, 0(x7); beq t0, x7, test_52_success; la x7, fail; jr x7; .align 3; test_52_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_52_success:
  test_53: li gp, 53; lw t0, 0(a0); addi a0, a0, 4; la x7, test_53_data; lw x7, 0(x7); beq t0, x7, test_53_success; la x7, fail; jr x7; .align 3; test_53_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_53_success:
  test_54: li gp, 54; lw t0, 0(a0); addi a0, a0, 4; la x7, test_54_data; lw x7, 0(x7); beq t0, x7, test_54_success; la x7, fail; jr x7; .align 3; test_54_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_54_success:
  test_55: li gp, 55; lw t0, 0(a0); addi a0, a0, 4; la x7, test_55_data; lw x7, 0(x7); beq t0, x7, test_55_success; la x7, fail; jr x7; .align 3; test_55_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_55_success:
  test_56: li gp, 56; lw t0, 0(a0); addi a0, a0, 4; la x7, test_56_data; lw x7, 0(x7); beq t0, x7, test_56_success; la x7, fail; jr x7; .align 3; test_56_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_56_success:
  test_57: li gp, 57; lw t0, 0(a0); addi a0, a0, 4; la x7, test_57_data; lw x7, 0(x7); beq t0, x7, test_57_success; la x7, fail; jr x7; .align 3; test_57_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_57_success:
 # Generating tests for VL: 2, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 448
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 2
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_58: li gp, 58; lw t0, 0(a0); addi a0, a0, 4; la x7, test_58_data; lw x7, 0(x7); beq t0, x7, test_58_success; la x7, fail; jr x7; .align 3; test_58_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_58_success:
  test_59: li gp, 59; lw t0, 0(a0); addi a0, a0, 4; la x7, test_59_data; lw x7, 0(x7); beq t0, x7, test_59_success; la x7, fail; jr x7; .align 3; test_59_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_59_success:
  test_60: li gp, 60; lw t0, 0(a0); addi a0, a0, 4; la x7, test_60_data; lw x7, 0(x7); beq t0, x7, test_60_success; la x7, fail; jr x7; .align 3; test_60_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_60_success:
  test_61: li gp, 61; lw t0, 0(a0); addi a0, a0, 4; la x7, test_61_data; lw x7, 0(x7); beq t0, x7, test_61_success; la x7, fail; jr x7; .align 3; test_61_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_61_success:
  test_62: li gp, 62; lw t0, 0(a0); addi a0, a0, 4; la x7, test_62_data; lw x7, 0(x7); beq t0, x7, test_62_success; la x7, fail; jr x7; .align 3; test_62_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_62_success:
  test_63: li gp, 63; lw t0, 0(a0); addi a0, a0, 4; la x7, test_63_data; lw x7, 0(x7); beq t0, x7, test_63_success; la x7, fail; jr x7; .align 3; test_63_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_63_success:
  test_64: li gp, 64; lw t0, 0(a0); addi a0, a0, 4; la x7, test_64_data; lw x7, 0(x7); beq t0, x7, test_64_success; la x7, fail; jr x7; .align 3; test_64_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_64_success:
  test_65: li gp, 65; lw t0, 0(a0); addi a0, a0, 4; la x7, test_65_data; lw x7, 0(x7); beq t0, x7, test_65_success; la x7, fail; jr x7; .align 3; test_65_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_65_success:
 # Generating tests for VL: 2, LMUL: m2, SEW: e8, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 512
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e8,m2,tu,mu
vle8.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 2
vsetvli t1, t0, e8,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e8,m2,tu,mu
vse8.v v28, (a0)
  test_66: li gp, 66; lw t0, 0(a0); addi a0, a0, 4; la x7, test_66_data; lw x7, 0(x7); beq t0, x7, test_66_success; la x7, fail; jr x7; .align 3; test_66_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_66_success:
  test_67: li gp, 67; lw t0, 0(a0); addi a0, a0, 4; la x7, test_67_data; lw x7, 0(x7); beq t0, x7, test_67_success; la x7, fail; jr x7; .align 3; test_67_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_67_success:
  test_68: li gp, 68; lw t0, 0(a0); addi a0, a0, 4; la x7, test_68_data; lw x7, 0(x7); beq t0, x7, test_68_success; la x7, fail; jr x7; .align 3; test_68_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_68_success:
  test_69: li gp, 69; lw t0, 0(a0); addi a0, a0, 4; la x7, test_69_data; lw x7, 0(x7); beq t0, x7, test_69_success; la x7, fail; jr x7; .align 3; test_69_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_69_success:
  test_70: li gp, 70; lw t0, 0(a0); addi a0, a0, 4; la x7, test_70_data; lw x7, 0(x7); beq t0, x7, test_70_success; la x7, fail; jr x7; .align 3; test_70_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_70_success:
  test_71: li gp, 71; lw t0, 0(a0); addi a0, a0, 4; la x7, test_71_data; lw x7, 0(x7); beq t0, x7, test_71_success; la x7, fail; jr x7; .align 3; test_71_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_71_success:
  test_72: li gp, 72; lw t0, 0(a0); addi a0, a0, 4; la x7, test_72_data; lw x7, 0(x7); beq t0, x7, test_72_success; la x7, fail; jr x7; .align 3; test_72_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_72_success:
  test_73: li gp, 73; lw t0, 0(a0); addi a0, a0, 4; la x7, test_73_data; lw x7, 0(x7); beq t0, x7, test_73_success; la x7, fail; jr x7; .align 3; test_73_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_73_success:
 # Generating tests for VL: 0, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 576
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_74: li gp, 74; lw t0, 0(a0); addi a0, a0, 4; la x7, test_74_data; lw x7, 0(x7); beq t0, x7, test_74_success; la x7, fail; jr x7; .align 3; test_74_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_74_success:
  test_75: li gp, 75; lw t0, 0(a0); addi a0, a0, 4; la x7, test_75_data; lw x7, 0(x7); beq t0, x7, test_75_success; la x7, fail; jr x7; .align 3; test_75_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_75_success:
  test_76: li gp, 76; lw t0, 0(a0); addi a0, a0, 4; la x7, test_76_data; lw x7, 0(x7); beq t0, x7, test_76_success; la x7, fail; jr x7; .align 3; test_76_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_76_success:
  test_77: li gp, 77; lw t0, 0(a0); addi a0, a0, 4; la x7, test_77_data; lw x7, 0(x7); beq t0, x7, test_77_success; la x7, fail; jr x7; .align 3; test_77_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_77_success:
  test_78: li gp, 78; lw t0, 0(a0); addi a0, a0, 4; la x7, test_78_data; lw x7, 0(x7); beq t0, x7, test_78_success; la x7, fail; jr x7; .align 3; test_78_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_78_success:
  test_79: li gp, 79; lw t0, 0(a0); addi a0, a0, 4; la x7, test_79_data; lw x7, 0(x7); beq t0, x7, test_79_success; la x7, fail; jr x7; .align 3; test_79_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_79_success:
  test_80: li gp, 80; lw t0, 0(a0); addi a0, a0, 4; la x7, test_80_data; lw x7, 0(x7); beq t0, x7, test_80_success; la x7, fail; jr x7; .align 3; test_80_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_80_success:
  test_81: li gp, 81; lw t0, 0(a0); addi a0, a0, 4; la x7, test_81_data; lw x7, 0(x7); beq t0, x7, test_81_success; la x7, fail; jr x7; .align 3; test_81_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_81_success:
 # Generating tests for VL: 7, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 640
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 7
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_82: li gp, 82; lw t0, 0(a0); addi a0, a0, 4; la x7, test_82_data; lw x7, 0(x7); beq t0, x7, test_82_success; la x7, fail; jr x7; .align 3; test_82_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_82_success:
  test_83: li gp, 83; lw t0, 0(a0); addi a0, a0, 4; la x7, test_83_data; lw x7, 0(x7); beq t0, x7, test_83_success; la x7, fail; jr x7; .align 3; test_83_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_83_success:
  test_84: li gp, 84; lw t0, 0(a0); addi a0, a0, 4; la x7, test_84_data; lw x7, 0(x7); beq t0, x7, test_84_success; la x7, fail; jr x7; .align 3; test_84_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_84_success:
  test_85: li gp, 85; lw t0, 0(a0); addi a0, a0, 4; la x7, test_85_data; lw x7, 0(x7); beq t0, x7, test_85_success; la x7, fail; jr x7; .align 3; test_85_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_85_success:
  test_86: li gp, 86; lw t0, 0(a0); addi a0, a0, 4; la x7, test_86_data; lw x7, 0(x7); beq t0, x7, test_86_success; la x7, fail; jr x7; .align 3; test_86_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_86_success:
  test_87: li gp, 87; lw t0, 0(a0); addi a0, a0, 4; la x7, test_87_data; lw x7, 0(x7); beq t0, x7, test_87_success; la x7, fail; jr x7; .align 3; test_87_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_87_success:
  test_88: li gp, 88; lw t0, 0(a0); addi a0, a0, 4; la x7, test_88_data; lw x7, 0(x7); beq t0, x7, test_88_success; la x7, fail; jr x7; .align 3; test_88_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_88_success:
  test_89: li gp, 89; lw t0, 0(a0); addi a0, a0, 4; la x7, test_89_data; lw x7, 0(x7); beq t0, x7, test_89_success; la x7, fail; jr x7; .align 3; test_89_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_89_success:
 # Generating tests for VL: 8, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 704
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 8
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_90: li gp, 90; lw t0, 0(a0); addi a0, a0, 4; la x7, test_90_data; lw x7, 0(x7); beq t0, x7, test_90_success; la x7, fail; jr x7; .align 3; test_90_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_90_success:
  test_91: li gp, 91; lw t0, 0(a0); addi a0, a0, 4; la x7, test_91_data; lw x7, 0(x7); beq t0, x7, test_91_success; la x7, fail; jr x7; .align 3; test_91_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_91_success:
  test_92: li gp, 92; lw t0, 0(a0); addi a0, a0, 4; la x7, test_92_data; lw x7, 0(x7); beq t0, x7, test_92_success; la x7, fail; jr x7; .align 3; test_92_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_92_success:
  test_93: li gp, 93; lw t0, 0(a0); addi a0, a0, 4; la x7, test_93_data; lw x7, 0(x7); beq t0, x7, test_93_success; la x7, fail; jr x7; .align 3; test_93_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_93_success:
  test_94: li gp, 94; lw t0, 0(a0); addi a0, a0, 4; la x7, test_94_data; lw x7, 0(x7); beq t0, x7, test_94_success; la x7, fail; jr x7; .align 3; test_94_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_94_success:
  test_95: li gp, 95; lw t0, 0(a0); addi a0, a0, 4; la x7, test_95_data; lw x7, 0(x7); beq t0, x7, test_95_success; la x7, fail; jr x7; .align 3; test_95_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_95_success:
  test_96: li gp, 96; lw t0, 0(a0); addi a0, a0, 4; la x7, test_96_data; lw x7, 0(x7); beq t0, x7, test_96_success; la x7, fail; jr x7; .align 3; test_96_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_96_success:
  test_97: li gp, 97; lw t0, 0(a0); addi a0, a0, 4; la x7, test_97_data; lw x7, 0(x7); beq t0, x7, test_97_success; la x7, fail; jr x7; .align 3; test_97_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_97_success:
 # Generating tests for VL: 16, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 768
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 16
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_98: li gp, 98; lw t0, 0(a0); addi a0, a0, 4; la x7, test_98_data; lw x7, 0(x7); beq t0, x7, test_98_success; la x7, fail; jr x7; .align 3; test_98_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_98_success:
  test_99: li gp, 99; lw t0, 0(a0); addi a0, a0, 4; la x7, test_99_data; lw x7, 0(x7); beq t0, x7, test_99_success; la x7, fail; jr x7; .align 3; test_99_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_99_success:
  test_100: li gp, 100; lw t0, 0(a0); addi a0, a0, 4; la x7, test_100_data; lw x7, 0(x7); beq t0, x7, test_100_success; la x7, fail; jr x7; .align 3; test_100_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_100_success:
  test_101: li gp, 101; lw t0, 0(a0); addi a0, a0, 4; la x7, test_101_data; lw x7, 0(x7); beq t0, x7, test_101_success; la x7, fail; jr x7; .align 3; test_101_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_101_success:
  test_102: li gp, 102; lw t0, 0(a0); addi a0, a0, 4; la x7, test_102_data; lw x7, 0(x7); beq t0, x7, test_102_success; la x7, fail; jr x7; .align 3; test_102_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_102_success:
  test_103: li gp, 103; lw t0, 0(a0); addi a0, a0, 4; la x7, test_103_data; lw x7, 0(x7); beq t0, x7, test_103_success; la x7, fail; jr x7; .align 3; test_103_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_103_success:
  test_104: li gp, 104; lw t0, 0(a0); addi a0, a0, 4; la x7, test_104_data; lw x7, 0(x7); beq t0, x7, test_104_success; la x7, fail; jr x7; .align 3; test_104_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_104_success:
  test_105: li gp, 105; lw t0, 0(a0); addi a0, a0, 4; la x7, test_105_data; lw x7, 0(x7); beq t0, x7, test_105_success; la x7, fail; jr x7; .align 3; test_105_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_105_success:
 # Generating tests for VL: 15, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 832
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 15
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_106: li gp, 106; lw t0, 0(a0); addi a0, a0, 4; la x7, test_106_data; lw x7, 0(x7); beq t0, x7, test_106_success; la x7, fail; jr x7; .align 3; test_106_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_106_success:
  test_107: li gp, 107; lw t0, 0(a0); addi a0, a0, 4; la x7, test_107_data; lw x7, 0(x7); beq t0, x7, test_107_success; la x7, fail; jr x7; .align 3; test_107_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_107_success:
  test_108: li gp, 108; lw t0, 0(a0); addi a0, a0, 4; la x7, test_108_data; lw x7, 0(x7); beq t0, x7, test_108_success; la x7, fail; jr x7; .align 3; test_108_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_108_success:
  test_109: li gp, 109; lw t0, 0(a0); addi a0, a0, 4; la x7, test_109_data; lw x7, 0(x7); beq t0, x7, test_109_success; la x7, fail; jr x7; .align 3; test_109_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_109_success:
  test_110: li gp, 110; lw t0, 0(a0); addi a0, a0, 4; la x7, test_110_data; lw x7, 0(x7); beq t0, x7, test_110_success; la x7, fail; jr x7; .align 3; test_110_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_110_success:
  test_111: li gp, 111; lw t0, 0(a0); addi a0, a0, 4; la x7, test_111_data; lw x7, 0(x7); beq t0, x7, test_111_success; la x7, fail; jr x7; .align 3; test_111_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_111_success:
  test_112: li gp, 112; lw t0, 0(a0); addi a0, a0, 4; la x7, test_112_data; lw x7, 0(x7); beq t0, x7, test_112_success; la x7, fail; jr x7; .align 3; test_112_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_112_success:
  test_113: li gp, 113; lw t0, 0(a0); addi a0, a0, 4; la x7, test_113_data; lw x7, 0(x7); beq t0, x7, test_113_success; la x7, fail; jr x7; .align 3; test_113_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_113_success:
 # Generating tests for VL: 17, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 896
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 17
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_114: li gp, 114; lw t0, 0(a0); addi a0, a0, 4; la x7, test_114_data; lw x7, 0(x7); beq t0, x7, test_114_success; la x7, fail; jr x7; .align 3; test_114_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_114_success:
  test_115: li gp, 115; lw t0, 0(a0); addi a0, a0, 4; la x7, test_115_data; lw x7, 0(x7); beq t0, x7, test_115_success; la x7, fail; jr x7; .align 3; test_115_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_115_success:
  test_116: li gp, 116; lw t0, 0(a0); addi a0, a0, 4; la x7, test_116_data; lw x7, 0(x7); beq t0, x7, test_116_success; la x7, fail; jr x7; .align 3; test_116_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_116_success:
  test_117: li gp, 117; lw t0, 0(a0); addi a0, a0, 4; la x7, test_117_data; lw x7, 0(x7); beq t0, x7, test_117_success; la x7, fail; jr x7; .align 3; test_117_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_117_success:
  test_118: li gp, 118; lw t0, 0(a0); addi a0, a0, 4; la x7, test_118_data; lw x7, 0(x7); beq t0, x7, test_118_success; la x7, fail; jr x7; .align 3; test_118_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_118_success:
  test_119: li gp, 119; lw t0, 0(a0); addi a0, a0, 4; la x7, test_119_data; lw x7, 0(x7); beq t0, x7, test_119_success; la x7, fail; jr x7; .align 3; test_119_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_119_success:
  test_120: li gp, 120; lw t0, 0(a0); addi a0, a0, 4; la x7, test_120_data; lw x7, 0(x7); beq t0, x7, test_120_success; la x7, fail; jr x7; .align 3; test_120_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_120_success:
  test_121: li gp, 121; lw t0, 0(a0); addi a0, a0, 4; la x7, test_121_data; lw x7, 0(x7); beq t0, x7, test_121_success; la x7, fail; jr x7; .align 3; test_121_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_121_success:
 # Generating tests for VL: 12, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 960
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_122: li gp, 122; lw t0, 0(a0); addi a0, a0, 4; la x7, test_122_data; lw x7, 0(x7); beq t0, x7, test_122_success; la x7, fail; jr x7; .align 3; test_122_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_122_success:
  test_123: li gp, 123; lw t0, 0(a0); addi a0, a0, 4; la x7, test_123_data; lw x7, 0(x7); beq t0, x7, test_123_success; la x7, fail; jr x7; .align 3; test_123_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_123_success:
  test_124: li gp, 124; lw t0, 0(a0); addi a0, a0, 4; la x7, test_124_data; lw x7, 0(x7); beq t0, x7, test_124_success; la x7, fail; jr x7; .align 3; test_124_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_124_success:
  test_125: li gp, 125; lw t0, 0(a0); addi a0, a0, 4; la x7, test_125_data; lw x7, 0(x7); beq t0, x7, test_125_success; la x7, fail; jr x7; .align 3; test_125_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_125_success:
  test_126: li gp, 126; lw t0, 0(a0); addi a0, a0, 4; la x7, test_126_data; lw x7, 0(x7); beq t0, x7, test_126_success; la x7, fail; jr x7; .align 3; test_126_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_126_success:
  test_127: li gp, 127; lw t0, 0(a0); addi a0, a0, 4; la x7, test_127_data; lw x7, 0(x7); beq t0, x7, test_127_success; la x7, fail; jr x7; .align 3; test_127_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_127_success:
  test_128: li gp, 128; lw t0, 0(a0); addi a0, a0, 4; la x7, test_128_data; lw x7, 0(x7); beq t0, x7, test_128_success; la x7, fail; jr x7; .align 3; test_128_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_128_success:
  test_129: li gp, 129; lw t0, 0(a0); addi a0, a0, 4; la x7, test_129_data; lw x7, 0(x7); beq t0, x7, test_129_success; la x7, fail; jr x7; .align 3; test_129_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_129_success:
 # Generating tests for VL: 12, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1024
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_130: li gp, 130; lw t0, 0(a0); addi a0, a0, 4; la x7, test_130_data; lw x7, 0(x7); beq t0, x7, test_130_success; la x7, fail; jr x7; .align 3; test_130_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_130_success:
  test_131: li gp, 131; lw t0, 0(a0); addi a0, a0, 4; la x7, test_131_data; lw x7, 0(x7); beq t0, x7, test_131_success; la x7, fail; jr x7; .align 3; test_131_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_131_success:
  test_132: li gp, 132; lw t0, 0(a0); addi a0, a0, 4; la x7, test_132_data; lw x7, 0(x7); beq t0, x7, test_132_success; la x7, fail; jr x7; .align 3; test_132_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_132_success:
  test_133: li gp, 133; lw t0, 0(a0); addi a0, a0, 4; la x7, test_133_data; lw x7, 0(x7); beq t0, x7, test_133_success; la x7, fail; jr x7; .align 3; test_133_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_133_success:
  test_134: li gp, 134; lw t0, 0(a0); addi a0, a0, 4; la x7, test_134_data; lw x7, 0(x7); beq t0, x7, test_134_success; la x7, fail; jr x7; .align 3; test_134_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_134_success:
  test_135: li gp, 135; lw t0, 0(a0); addi a0, a0, 4; la x7, test_135_data; lw x7, 0(x7); beq t0, x7, test_135_success; la x7, fail; jr x7; .align 3; test_135_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_135_success:
  test_136: li gp, 136; lw t0, 0(a0); addi a0, a0, 4; la x7, test_136_data; lw x7, 0(x7); beq t0, x7, test_136_success; la x7, fail; jr x7; .align 3; test_136_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_136_success:
  test_137: li gp, 137; lw t0, 0(a0); addi a0, a0, 4; la x7, test_137_data; lw x7, 0(x7); beq t0, x7, test_137_success; la x7, fail; jr x7; .align 3; test_137_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_137_success:
 # Generating tests for VL: 12, LMUL: m2, SEW: e16, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1088
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e16,m2,tu,mu
vle16.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 12
vsetvli t1, t0, e16,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e16,m2,tu,mu
vse16.v v28, (a0)
  test_138: li gp, 138; lw t0, 0(a0); addi a0, a0, 4; la x7, test_138_data; lw x7, 0(x7); beq t0, x7, test_138_success; la x7, fail; jr x7; .align 3; test_138_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_138_success:
  test_139: li gp, 139; lw t0, 0(a0); addi a0, a0, 4; la x7, test_139_data; lw x7, 0(x7); beq t0, x7, test_139_success; la x7, fail; jr x7; .align 3; test_139_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_139_success:
  test_140: li gp, 140; lw t0, 0(a0); addi a0, a0, 4; la x7, test_140_data; lw x7, 0(x7); beq t0, x7, test_140_success; la x7, fail; jr x7; .align 3; test_140_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_140_success:
  test_141: li gp, 141; lw t0, 0(a0); addi a0, a0, 4; la x7, test_141_data; lw x7, 0(x7); beq t0, x7, test_141_success; la x7, fail; jr x7; .align 3; test_141_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_141_success:
  test_142: li gp, 142; lw t0, 0(a0); addi a0, a0, 4; la x7, test_142_data; lw x7, 0(x7); beq t0, x7, test_142_success; la x7, fail; jr x7; .align 3; test_142_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_142_success:
  test_143: li gp, 143; lw t0, 0(a0); addi a0, a0, 4; la x7, test_143_data; lw x7, 0(x7); beq t0, x7, test_143_success; la x7, fail; jr x7; .align 3; test_143_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_143_success:
  test_144: li gp, 144; lw t0, 0(a0); addi a0, a0, 4; la x7, test_144_data; lw x7, 0(x7); beq t0, x7, test_144_success; la x7, fail; jr x7; .align 3; test_144_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_144_success:
  test_145: li gp, 145; lw t0, 0(a0); addi a0, a0, 4; la x7, test_145_data; lw x7, 0(x7); beq t0, x7, test_145_success; la x7, fail; jr x7; .align 3; test_145_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_145_success:
 # Generating tests for VL: 0, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1152
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_146: li gp, 146; lw t0, 0(a0); addi a0, a0, 4; la x7, test_146_data; lw x7, 0(x7); beq t0, x7, test_146_success; la x7, fail; jr x7; .align 3; test_146_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_146_success:
  test_147: li gp, 147; lw t0, 0(a0); addi a0, a0, 4; la x7, test_147_data; lw x7, 0(x7); beq t0, x7, test_147_success; la x7, fail; jr x7; .align 3; test_147_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_147_success:
  test_148: li gp, 148; lw t0, 0(a0); addi a0, a0, 4; la x7, test_148_data; lw x7, 0(x7); beq t0, x7, test_148_success; la x7, fail; jr x7; .align 3; test_148_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_148_success:
  test_149: li gp, 149; lw t0, 0(a0); addi a0, a0, 4; la x7, test_149_data; lw x7, 0(x7); beq t0, x7, test_149_success; la x7, fail; jr x7; .align 3; test_149_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_149_success:
  test_150: li gp, 150; lw t0, 0(a0); addi a0, a0, 4; la x7, test_150_data; lw x7, 0(x7); beq t0, x7, test_150_success; la x7, fail; jr x7; .align 3; test_150_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_150_success:
  test_151: li gp, 151; lw t0, 0(a0); addi a0, a0, 4; la x7, test_151_data; lw x7, 0(x7); beq t0, x7, test_151_success; la x7, fail; jr x7; .align 3; test_151_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_151_success:
  test_152: li gp, 152; lw t0, 0(a0); addi a0, a0, 4; la x7, test_152_data; lw x7, 0(x7); beq t0, x7, test_152_success; la x7, fail; jr x7; .align 3; test_152_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_152_success:
  test_153: li gp, 153; lw t0, 0(a0); addi a0, a0, 4; la x7, test_153_data; lw x7, 0(x7); beq t0, x7, test_153_success; la x7, fail; jr x7; .align 3; test_153_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_153_success:
 # Generating tests for VL: 3, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1216
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 3
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_154: li gp, 154; lw t0, 0(a0); addi a0, a0, 4; la x7, test_154_data; lw x7, 0(x7); beq t0, x7, test_154_success; la x7, fail; jr x7; .align 3; test_154_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_154_success:
  test_155: li gp, 155; lw t0, 0(a0); addi a0, a0, 4; la x7, test_155_data; lw x7, 0(x7); beq t0, x7, test_155_success; la x7, fail; jr x7; .align 3; test_155_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_155_success:
  test_156: li gp, 156; lw t0, 0(a0); addi a0, a0, 4; la x7, test_156_data; lw x7, 0(x7); beq t0, x7, test_156_success; la x7, fail; jr x7; .align 3; test_156_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_156_success:
  test_157: li gp, 157; lw t0, 0(a0); addi a0, a0, 4; la x7, test_157_data; lw x7, 0(x7); beq t0, x7, test_157_success; la x7, fail; jr x7; .align 3; test_157_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_157_success:
  test_158: li gp, 158; lw t0, 0(a0); addi a0, a0, 4; la x7, test_158_data; lw x7, 0(x7); beq t0, x7, test_158_success; la x7, fail; jr x7; .align 3; test_158_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_158_success:
  test_159: li gp, 159; lw t0, 0(a0); addi a0, a0, 4; la x7, test_159_data; lw x7, 0(x7); beq t0, x7, test_159_success; la x7, fail; jr x7; .align 3; test_159_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_159_success:
  test_160: li gp, 160; lw t0, 0(a0); addi a0, a0, 4; la x7, test_160_data; lw x7, 0(x7); beq t0, x7, test_160_success; la x7, fail; jr x7; .align 3; test_160_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_160_success:
  test_161: li gp, 161; lw t0, 0(a0); addi a0, a0, 4; la x7, test_161_data; lw x7, 0(x7); beq t0, x7, test_161_success; la x7, fail; jr x7; .align 3; test_161_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_161_success:
 # Generating tests for VL: 4, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1280
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 4
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_162: li gp, 162; lw t0, 0(a0); addi a0, a0, 4; la x7, test_162_data; lw x7, 0(x7); beq t0, x7, test_162_success; la x7, fail; jr x7; .align 3; test_162_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_162_success:
  test_163: li gp, 163; lw t0, 0(a0); addi a0, a0, 4; la x7, test_163_data; lw x7, 0(x7); beq t0, x7, test_163_success; la x7, fail; jr x7; .align 3; test_163_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_163_success:
  test_164: li gp, 164; lw t0, 0(a0); addi a0, a0, 4; la x7, test_164_data; lw x7, 0(x7); beq t0, x7, test_164_success; la x7, fail; jr x7; .align 3; test_164_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_164_success:
  test_165: li gp, 165; lw t0, 0(a0); addi a0, a0, 4; la x7, test_165_data; lw x7, 0(x7); beq t0, x7, test_165_success; la x7, fail; jr x7; .align 3; test_165_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_165_success:
  test_166: li gp, 166; lw t0, 0(a0); addi a0, a0, 4; la x7, test_166_data; lw x7, 0(x7); beq t0, x7, test_166_success; la x7, fail; jr x7; .align 3; test_166_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_166_success:
  test_167: li gp, 167; lw t0, 0(a0); addi a0, a0, 4; la x7, test_167_data; lw x7, 0(x7); beq t0, x7, test_167_success; la x7, fail; jr x7; .align 3; test_167_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_167_success:
  test_168: li gp, 168; lw t0, 0(a0); addi a0, a0, 4; la x7, test_168_data; lw x7, 0(x7); beq t0, x7, test_168_success; la x7, fail; jr x7; .align 3; test_168_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_168_success:
  test_169: li gp, 169; lw t0, 0(a0); addi a0, a0, 4; la x7, test_169_data; lw x7, 0(x7); beq t0, x7, test_169_success; la x7, fail; jr x7; .align 3; test_169_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_169_success:
 # Generating tests for VL: 8, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1344
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 8
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_170: li gp, 170; lw t0, 0(a0); addi a0, a0, 4; la x7, test_170_data; lw x7, 0(x7); beq t0, x7, test_170_success; la x7, fail; jr x7; .align 3; test_170_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_170_success:
  test_171: li gp, 171; lw t0, 0(a0); addi a0, a0, 4; la x7, test_171_data; lw x7, 0(x7); beq t0, x7, test_171_success; la x7, fail; jr x7; .align 3; test_171_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_171_success:
  test_172: li gp, 172; lw t0, 0(a0); addi a0, a0, 4; la x7, test_172_data; lw x7, 0(x7); beq t0, x7, test_172_success; la x7, fail; jr x7; .align 3; test_172_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_172_success:
  test_173: li gp, 173; lw t0, 0(a0); addi a0, a0, 4; la x7, test_173_data; lw x7, 0(x7); beq t0, x7, test_173_success; la x7, fail; jr x7; .align 3; test_173_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_173_success:
  test_174: li gp, 174; lw t0, 0(a0); addi a0, a0, 4; la x7, test_174_data; lw x7, 0(x7); beq t0, x7, test_174_success; la x7, fail; jr x7; .align 3; test_174_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_174_success:
  test_175: li gp, 175; lw t0, 0(a0); addi a0, a0, 4; la x7, test_175_data; lw x7, 0(x7); beq t0, x7, test_175_success; la x7, fail; jr x7; .align 3; test_175_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_175_success:
  test_176: li gp, 176; lw t0, 0(a0); addi a0, a0, 4; la x7, test_176_data; lw x7, 0(x7); beq t0, x7, test_176_success; la x7, fail; jr x7; .align 3; test_176_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_176_success:
  test_177: li gp, 177; lw t0, 0(a0); addi a0, a0, 4; la x7, test_177_data; lw x7, 0(x7); beq t0, x7, test_177_success; la x7, fail; jr x7; .align 3; test_177_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_177_success:
 # Generating tests for VL: 7, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1408
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 7
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_178: li gp, 178; lw t0, 0(a0); addi a0, a0, 4; la x7, test_178_data; lw x7, 0(x7); beq t0, x7, test_178_success; la x7, fail; jr x7; .align 3; test_178_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_178_success:
  test_179: li gp, 179; lw t0, 0(a0); addi a0, a0, 4; la x7, test_179_data; lw x7, 0(x7); beq t0, x7, test_179_success; la x7, fail; jr x7; .align 3; test_179_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_179_success:
  test_180: li gp, 180; lw t0, 0(a0); addi a0, a0, 4; la x7, test_180_data; lw x7, 0(x7); beq t0, x7, test_180_success; la x7, fail; jr x7; .align 3; test_180_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_180_success:
  test_181: li gp, 181; lw t0, 0(a0); addi a0, a0, 4; la x7, test_181_data; lw x7, 0(x7); beq t0, x7, test_181_success; la x7, fail; jr x7; .align 3; test_181_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_181_success:
  test_182: li gp, 182; lw t0, 0(a0); addi a0, a0, 4; la x7, test_182_data; lw x7, 0(x7); beq t0, x7, test_182_success; la x7, fail; jr x7; .align 3; test_182_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_182_success:
  test_183: li gp, 183; lw t0, 0(a0); addi a0, a0, 4; la x7, test_183_data; lw x7, 0(x7); beq t0, x7, test_183_success; la x7, fail; jr x7; .align 3; test_183_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_183_success:
  test_184: li gp, 184; lw t0, 0(a0); addi a0, a0, 4; la x7, test_184_data; lw x7, 0(x7); beq t0, x7, test_184_success; la x7, fail; jr x7; .align 3; test_184_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_184_success:
  test_185: li gp, 185; lw t0, 0(a0); addi a0, a0, 4; la x7, test_185_data; lw x7, 0(x7); beq t0, x7, test_185_success; la x7, fail; jr x7; .align 3; test_185_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_185_success:
 # Generating tests for VL: 9, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1472
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 9
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_186: li gp, 186; lw t0, 0(a0); addi a0, a0, 4; la x7, test_186_data; lw x7, 0(x7); beq t0, x7, test_186_success; la x7, fail; jr x7; .align 3; test_186_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_186_success:
  test_187: li gp, 187; lw t0, 0(a0); addi a0, a0, 4; la x7, test_187_data; lw x7, 0(x7); beq t0, x7, test_187_success; la x7, fail; jr x7; .align 3; test_187_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_187_success:
  test_188: li gp, 188; lw t0, 0(a0); addi a0, a0, 4; la x7, test_188_data; lw x7, 0(x7); beq t0, x7, test_188_success; la x7, fail; jr x7; .align 3; test_188_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_188_success:
  test_189: li gp, 189; lw t0, 0(a0); addi a0, a0, 4; la x7, test_189_data; lw x7, 0(x7); beq t0, x7, test_189_success; la x7, fail; jr x7; .align 3; test_189_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_189_success:
  test_190: li gp, 190; lw t0, 0(a0); addi a0, a0, 4; la x7, test_190_data; lw x7, 0(x7); beq t0, x7, test_190_success; la x7, fail; jr x7; .align 3; test_190_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_190_success:
  test_191: li gp, 191; lw t0, 0(a0); addi a0, a0, 4; la x7, test_191_data; lw x7, 0(x7); beq t0, x7, test_191_success; la x7, fail; jr x7; .align 3; test_191_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_191_success:
  test_192: li gp, 192; lw t0, 0(a0); addi a0, a0, 4; la x7, test_192_data; lw x7, 0(x7); beq t0, x7, test_192_success; la x7, fail; jr x7; .align 3; test_192_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_192_success:
  test_193: li gp, 193; lw t0, 0(a0); addi a0, a0, 4; la x7, test_193_data; lw x7, 0(x7); beq t0, x7, test_193_success; la x7, fail; jr x7; .align 3; test_193_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_193_success:
 # Generating tests for VL: 0, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1536
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_194: li gp, 194; lw t0, 0(a0); addi a0, a0, 4; la x7, test_194_data; lw x7, 0(x7); beq t0, x7, test_194_success; la x7, fail; jr x7; .align 3; test_194_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_194_success:
  test_195: li gp, 195; lw t0, 0(a0); addi a0, a0, 4; la x7, test_195_data; lw x7, 0(x7); beq t0, x7, test_195_success; la x7, fail; jr x7; .align 3; test_195_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_195_success:
  test_196: li gp, 196; lw t0, 0(a0); addi a0, a0, 4; la x7, test_196_data; lw x7, 0(x7); beq t0, x7, test_196_success; la x7, fail; jr x7; .align 3; test_196_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_196_success:
  test_197: li gp, 197; lw t0, 0(a0); addi a0, a0, 4; la x7, test_197_data; lw x7, 0(x7); beq t0, x7, test_197_success; la x7, fail; jr x7; .align 3; test_197_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_197_success:
  test_198: li gp, 198; lw t0, 0(a0); addi a0, a0, 4; la x7, test_198_data; lw x7, 0(x7); beq t0, x7, test_198_success; la x7, fail; jr x7; .align 3; test_198_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_198_success:
  test_199: li gp, 199; lw t0, 0(a0); addi a0, a0, 4; la x7, test_199_data; lw x7, 0(x7); beq t0, x7, test_199_success; la x7, fail; jr x7; .align 3; test_199_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_199_success:
  test_200: li gp, 200; lw t0, 0(a0); addi a0, a0, 4; la x7, test_200_data; lw x7, 0(x7); beq t0, x7, test_200_success; la x7, fail; jr x7; .align 3; test_200_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_200_success:
  test_201: li gp, 201; lw t0, 0(a0); addi a0, a0, 4; la x7, test_201_data; lw x7, 0(x7); beq t0, x7, test_201_success; la x7, fail; jr x7; .align 3; test_201_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_201_success:
 # Generating tests for VL: 0, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1600
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_202: li gp, 202; lw t0, 0(a0); addi a0, a0, 4; la x7, test_202_data; lw x7, 0(x7); beq t0, x7, test_202_success; la x7, fail; jr x7; .align 3; test_202_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_202_success:
  test_203: li gp, 203; lw t0, 0(a0); addi a0, a0, 4; la x7, test_203_data; lw x7, 0(x7); beq t0, x7, test_203_success; la x7, fail; jr x7; .align 3; test_203_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_203_success:
  test_204: li gp, 204; lw t0, 0(a0); addi a0, a0, 4; la x7, test_204_data; lw x7, 0(x7); beq t0, x7, test_204_success; la x7, fail; jr x7; .align 3; test_204_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_204_success:
  test_205: li gp, 205; lw t0, 0(a0); addi a0, a0, 4; la x7, test_205_data; lw x7, 0(x7); beq t0, x7, test_205_success; la x7, fail; jr x7; .align 3; test_205_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_205_success:
  test_206: li gp, 206; lw t0, 0(a0); addi a0, a0, 4; la x7, test_206_data; lw x7, 0(x7); beq t0, x7, test_206_success; la x7, fail; jr x7; .align 3; test_206_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_206_success:
  test_207: li gp, 207; lw t0, 0(a0); addi a0, a0, 4; la x7, test_207_data; lw x7, 0(x7); beq t0, x7, test_207_success; la x7, fail; jr x7; .align 3; test_207_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_207_success:
  test_208: li gp, 208; lw t0, 0(a0); addi a0, a0, 4; la x7, test_208_data; lw x7, 0(x7); beq t0, x7, test_208_success; la x7, fail; jr x7; .align 3; test_208_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_208_success:
  test_209: li gp, 209; lw t0, 0(a0); addi a0, a0, 4; la x7, test_209_data; lw x7, 0(x7); beq t0, x7, test_209_success; la x7, fail; jr x7; .align 3; test_209_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_209_success:
 # Generating tests for VL: 0, LMUL: m2, SEW: e32, Mask: false
# Initialize rounding mode CSR
csrwi vxrm, 0 # rnu (round-to-nearest-up)
# Move a0 to test data area.
la a0, testdata
li a5, 1664
add a0, a0, a5
# Load data into v28 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v28, (a0)
li t1, 32
add a0, a0, t1
# Load data into v26 register group.
vsetvli t1, x0, e32,m2,tu,mu
vle32.v v26, (a0)
# -------------- TEST BEGIN --------------
li t0, 0
vsetvli t1, t0, e32,m2,tu,mu
vmv2r.v v28, v26
# -------------- TEST END --------------
la a0, resultdata
# Store v28 register group into result data area.
vsetvli t1, x0, e32,m2,tu,mu
vse32.v v28, (a0)
  test_210: li gp, 210; lw t0, 0(a0); addi a0, a0, 4; la x7, test_210_data; lw x7, 0(x7); beq t0, x7, test_210_success; la x7, fail; jr x7; .align 3; test_210_data: .quad ((0xf05f7f2b) & ((1 << (32 - 1) << 1) - 1)); test_210_success:
  test_211: li gp, 211; lw t0, 0(a0); addi a0, a0, 4; la x7, test_211_data; lw x7, 0(x7); beq t0, x7, test_211_success; la x7, fail; jr x7; .align 3; test_211_data: .quad ((0x9efd115d) & ((1 << (32 - 1) << 1) - 1)); test_211_success:
  test_212: li gp, 212; lw t0, 0(a0); addi a0, a0, 4; la x7, test_212_data; lw x7, 0(x7); beq t0, x7, test_212_success; la x7, fail; jr x7; .align 3; test_212_data: .quad ((0x39600a9a) & ((1 << (32 - 1) << 1) - 1)); test_212_success:
  test_213: li gp, 213; lw t0, 0(a0); addi a0, a0, 4; la x7, test_213_data; lw x7, 0(x7); beq t0, x7, test_213_success; la x7, fail; jr x7; .align 3; test_213_data: .quad ((0x15500b3b) & ((1 << (32 - 1) << 1) - 1)); test_213_success:
  test_214: li gp, 214; lw t0, 0(a0); addi a0, a0, 4; la x7, test_214_data; lw x7, 0(x7); beq t0, x7, test_214_success; la x7, fail; jr x7; .align 3; test_214_data: .quad ((0x421b89f5) & ((1 << (32 - 1) << 1) - 1)); test_214_success:
  test_215: li gp, 215; lw t0, 0(a0); addi a0, a0, 4; la x7, test_215_data; lw x7, 0(x7); beq t0, x7, test_215_success; la x7, fail; jr x7; .align 3; test_215_data: .quad ((0x90b9566a) & ((1 << (32 - 1) << 1) - 1)); test_215_success:
  test_216: li gp, 216; lw t0, 0(a0); addi a0, a0, 4; la x7, test_216_data; lw x7, 0(x7); beq t0, x7, test_216_success; la x7, fail; jr x7; .align 3; test_216_data: .quad ((0x9a69193a) & ((1 << (32 - 1) << 1) - 1)); test_216_success:
  test_217: li gp, 217; lw t0, 0(a0); addi a0, a0, 4; la x7, test_217_data; lw x7, 0(x7); beq t0, x7, test_217_success; la x7, fail; jr x7; .align 3; test_217_data: .quad ((0xd6eacf8) & ((1 << (32 - 1) << 1) - 1)); test_217_success:
  bne x0, gp, pass; fail: fence; 1: beqz gp, 1b; sll gp, gp, 1; or gp, gp, 1; ecall; pass: fence; li gp, 1; ecall
unimp
  .data
.pushsection .tohost, "aw", @progbits; .align 6; .global tohost; tohost: .dword 0; .align 6; .global fromhost; fromhost: .dword 0; .popsection; .align 4; .global begin_signature; begin_signature:
 # Reserve space for test data.
resultdata:
  .zero 1024
testdata:
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
  .quad 0x4caa98378257619c
  .quad 0x456091ce64a9701b
  .quad 0xc59f38c9991964f3
  .quad 0xb9ebbdaca012c06
  .quad 0x9efd115df05f7f2b
  .quad 0x15500b3b39600a9a
  .quad 0x90b9566a421b89f5
  .quad 0xd6eacf89a69193a
.align 4; .global end_signature; end_signature:
