# This file is automatically generated. Do not edit.
# Instruction: vsetvl
#-----------------------------------------------------------------------
# Helper macros
#-----------------------------------------------------------------------
# We use a macro hack to simpify code generation for various numbers
# of bubble cycles.
#-----------------------------------------------------------------------
# RV64UI MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for instructions with immediate operand
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests for an instruction with register-register operands
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test memory instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test jump instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# RV64UF MACROS
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Tests floating-point instructions
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Pass and fail code (assumes test num is in gp)
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# Test data section
#-----------------------------------------------------------------------
.macro init; li t5, (0x00000600 & (0x00000600 >> 1)); csrs mstatus, t5; csrwi vcsr, 0;; .endm
.section .text.init; .align 6; .weak mtvec_handler; .globl _start; _start: j reset_vector; .align 2; trap_vector: csrr t5, mcause; li t6, 0xb; beq t5, t6, write_tohost; li t6, 0x8; beq t5, t6, write_tohost; li t6, 0x9; beq t5, t6, write_tohost; la t5, mtvec_handler; beqz t5, 1f; jr t5; 1: ori gp, gp, 1337; write_tohost: sw gp, tohost, t5; sw zero, tohost + 4, t5; j write_tohost; reset_vector: li gp, 0; la t0, trap_vector; csrw mtvec, t0; init;
 # Zero all vector registers
vsetvli t0, x0, e8,m8,tu,mu
vmv.v.i v0, 0x0
vmv.v.i v8, 0x0
vmv.v.i v16, 0x0
vmv.v.i v24, 0x0
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 0
vsetvl t0, t1, t2
csrr a4, vstart
test_3: li gp, 3; ; la x7, test_3_data; lw x7, 0(x7); beq a4, x7, test_3_success; la x7, fail; jr x7; .align 3; test_3_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_3_success:
csrr a4, vtype
test_4: li gp, 4; ; la x7, test_4_data; lw x7, 0(x7); beq a4, x7, test_4_success; la x7, fail; jr x7; .align 3; test_4_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_4_success:
csrr a4, vl
test_5: li gp, 5; ; la x7, test_5_data; lw x7, 0(x7); beq a4, x7, test_5_success; la x7, fail; jr x7; .align 3; test_5_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_5_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 0
vsetvl t0, zero, t2
csrr a4, vstart
test_6: li gp, 6; ; la x7, test_6_data; lw x7, 0(x7); beq a4, x7, test_6_success; la x7, fail; jr x7; .align 3; test_6_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_6_success:
csrr a4, vtype
test_7: li gp, 7; ; la x7, test_7_data; lw x7, 0(x7); beq a4, x7, test_7_success; la x7, fail; jr x7; .align 3; test_7_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_7_success:
csrr a4, vl
test_8: li gp, 8; ; la x7, test_8_data; lw x7, 0(x7); beq a4, x7, test_8_success; la x7, fail; jr x7; .align 3; test_8_data: .quad ((16) & ((1 << (32 - 1) << 1) - 1)); test_8_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 0
vsetvl zero, zero, t2
csrr a4, vstart
test_9: li gp, 9; ; la x7, test_9_data; lw x7, 0(x7); beq a4, x7, test_9_success; la x7, fail; jr x7; .align 3; test_9_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_9_success:
csrr a4, vtype
test_10: li gp, 10; ; la x7, test_10_data; lw x7, 0(x7); beq a4, x7, test_10_success; la x7, fail; jr x7; .align 3; test_10_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_10_success:
csrr a4, vl
test_11: li gp, 11; ; la x7, test_11_data; lw x7, 0(x7); beq a4, x7, test_11_success; la x7, fail; jr x7; .align 3; test_11_data: .quad ((16) & ((1 << (32 - 1) << 1) - 1)); test_11_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 10
vsetvl t0, t1, t2
csrr a4, vstart
test_12: li gp, 12; ; la x7, test_12_data; lw x7, 0(x7); beq a4, x7, test_12_success; la x7, fail; jr x7; .align 3; test_12_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_12_success:
csrr a4, vtype
test_13: li gp, 13; ; la x7, test_13_data; lw x7, 0(x7); beq a4, x7, test_13_success; la x7, fail; jr x7; .align 3; test_13_data: .quad ((10) & ((1 << (32 - 1) << 1) - 1)); test_13_success:
csrr a4, vl
test_14: li gp, 14; ; la x7, test_14_data; lw x7, 0(x7); beq a4, x7, test_14_success; la x7, fail; jr x7; .align 3; test_14_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_14_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 10
vsetvl t0, zero, t2
csrr a4, vstart
test_15: li gp, 15; ; la x7, test_15_data; lw x7, 0(x7); beq a4, x7, test_15_success; la x7, fail; jr x7; .align 3; test_15_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_15_success:
csrr a4, vtype
test_16: li gp, 16; ; la x7, test_16_data; lw x7, 0(x7); beq a4, x7, test_16_success; la x7, fail; jr x7; .align 3; test_16_data: .quad ((10) & ((1 << (32 - 1) << 1) - 1)); test_16_success:
csrr a4, vl
test_17: li gp, 17; ; la x7, test_17_data; lw x7, 0(x7); beq a4, x7, test_17_success; la x7, fail; jr x7; .align 3; test_17_data: .quad ((32) & ((1 << (32 - 1) << 1) - 1)); test_17_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 10
vsetvl zero, zero, t2
csrr a4, vstart
test_18: li gp, 18; ; la x7, test_18_data; lw x7, 0(x7); beq a4, x7, test_18_success; la x7, fail; jr x7; .align 3; test_18_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_18_success:
csrr a4, vtype
test_19: li gp, 19; ; la x7, test_19_data; lw x7, 0(x7); beq a4, x7, test_19_success; la x7, fail; jr x7; .align 3; test_19_data: .quad ((10) & ((1 << (32 - 1) << 1) - 1)); test_19_success:
csrr a4, vl
test_20: li gp, 20; ; la x7, test_20_data; lw x7, 0(x7); beq a4, x7, test_20_success; la x7, fail; jr x7; .align 3; test_20_data: .quad ((32) & ((1 << (32 - 1) << 1) - 1)); test_20_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 13
vsetvl t0, t1, t2
csrr a4, vstart
test_21: li gp, 21; ; la x7, test_21_data; lw x7, 0(x7); beq a4, x7, test_21_success; la x7, fail; jr x7; .align 3; test_21_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_21_success:
csrr a4, vtype
test_22: li gp, 22; ; la x7, test_22_data; lw x7, 0(x7); beq a4, x7, test_22_success; la x7, fail; jr x7; .align 3; test_22_data: .quad ((2147483648) & ((1 << (32 - 1) << 1) - 1)); test_22_success:
csrr a4, vl
test_23: li gp, 23; ; la x7, test_23_data; lw x7, 0(x7); beq a4, x7, test_23_success; la x7, fail; jr x7; .align 3; test_23_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_23_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 13
vsetvl t0, zero, t2
csrr a4, vstart
test_24: li gp, 24; ; la x7, test_24_data; lw x7, 0(x7); beq a4, x7, test_24_success; la x7, fail; jr x7; .align 3; test_24_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_24_success:
csrr a4, vtype
test_25: li gp, 25; ; la x7, test_25_data; lw x7, 0(x7); beq a4, x7, test_25_success; la x7, fail; jr x7; .align 3; test_25_data: .quad ((2147483648) & ((1 << (32 - 1) << 1) - 1)); test_25_success:
csrr a4, vl
test_26: li gp, 26; ; la x7, test_26_data; lw x7, 0(x7); beq a4, x7, test_26_success; la x7, fail; jr x7; .align 3; test_26_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_26_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 0
li t1, 0
li t2, 13
vsetvl zero, zero, t2
csrr a4, vstart
test_27: li gp, 27; ; la x7, test_27_data; lw x7, 0(x7); beq a4, x7, test_27_success; la x7, fail; jr x7; .align 3; test_27_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_27_success:
csrr a4, vtype
test_28: li gp, 28; ; la x7, test_28_data; lw x7, 0(x7); beq a4, x7, test_28_success; la x7, fail; jr x7; .align 3; test_28_data: .quad ((2147483648) & ((1 << (32 - 1) << 1) - 1)); test_28_success:
csrr a4, vl
test_29: li gp, 29; ; la x7, test_29_data; lw x7, 0(x7); beq a4, x7, test_29_success; la x7, fail; jr x7; .align 3; test_29_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_29_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 1
li t1, 1
li t2, 2
vsetvl t0, t1, t2
csrr a4, vstart
test_30: li gp, 30; ; la x7, test_30_data; lw x7, 0(x7); beq a4, x7, test_30_success; la x7, fail; jr x7; .align 3; test_30_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_30_success:
csrr a4, vtype
test_31: li gp, 31; ; la x7, test_31_data; lw x7, 0(x7); beq a4, x7, test_31_success; la x7, fail; jr x7; .align 3; test_31_data: .quad ((2) & ((1 << (32 - 1) << 1) - 1)); test_31_success:
csrr a4, vl
test_32: li gp, 32; ; la x7, test_32_data; lw x7, 0(x7); beq a4, x7, test_32_success; la x7, fail; jr x7; .align 3; test_32_data: .quad ((1) & ((1 << (32 - 1) << 1) - 1)); test_32_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 1
li t1, 1
li t2, 2
vsetvl t0, zero, t2
csrr a4, vstart
test_33: li gp, 33; ; la x7, test_33_data; lw x7, 0(x7); beq a4, x7, test_33_success; la x7, fail; jr x7; .align 3; test_33_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_33_success:
csrr a4, vtype
test_34: li gp, 34; ; la x7, test_34_data; lw x7, 0(x7); beq a4, x7, test_34_success; la x7, fail; jr x7; .align 3; test_34_data: .quad ((2) & ((1 << (32 - 1) << 1) - 1)); test_34_success:
csrr a4, vl
test_35: li gp, 35; ; la x7, test_35_data; lw x7, 0(x7); beq a4, x7, test_35_success; la x7, fail; jr x7; .align 3; test_35_data: .quad ((64) & ((1 << (32 - 1) << 1) - 1)); test_35_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 1
li t1, 1
li t2, 2
vsetvl zero, zero, t2
csrr a4, vstart
test_36: li gp, 36; ; la x7, test_36_data; lw x7, 0(x7); beq a4, x7, test_36_success; la x7, fail; jr x7; .align 3; test_36_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_36_success:
csrr a4, vtype
test_37: li gp, 37; ; la x7, test_37_data; lw x7, 0(x7); beq a4, x7, test_37_success; la x7, fail; jr x7; .align 3; test_37_data: .quad ((2) & ((1 << (32 - 1) << 1) - 1)); test_37_success:
csrr a4, vl
test_38: li gp, 38; ; la x7, test_38_data; lw x7, 0(x7); beq a4, x7, test_38_success; la x7, fail; jr x7; .align 3; test_38_data: .quad ((64) & ((1 << (32 - 1) << 1) - 1)); test_38_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 3
li t1, 3
li t2, 15
vsetvl t0, t1, t2
csrr a4, vstart
test_39: li gp, 39; ; la x7, test_39_data; lw x7, 0(x7); beq a4, x7, test_39_success; la x7, fail; jr x7; .align 3; test_39_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_39_success:
csrr a4, vtype
test_40: li gp, 40; ; la x7, test_40_data; lw x7, 0(x7); beq a4, x7, test_40_success; la x7, fail; jr x7; .align 3; test_40_data: .quad ((15) & ((1 << (32 - 1) << 1) - 1)); test_40_success:
csrr a4, vl
test_41: li gp, 41; ; la x7, test_41_data; lw x7, 0(x7); beq a4, x7, test_41_success; la x7, fail; jr x7; .align 3; test_41_data: .quad ((3) & ((1 << (32 - 1) << 1) - 1)); test_41_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 3
li t1, 3
li t2, 15
vsetvl t0, zero, t2
csrr a4, vstart
test_42: li gp, 42; ; la x7, test_42_data; lw x7, 0(x7); beq a4, x7, test_42_success; la x7, fail; jr x7; .align 3; test_42_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_42_success:
csrr a4, vtype
test_43: li gp, 43; ; la x7, test_43_data; lw x7, 0(x7); beq a4, x7, test_43_success; la x7, fail; jr x7; .align 3; test_43_data: .quad ((15) & ((1 << (32 - 1) << 1) - 1)); test_43_success:
csrr a4, vl
test_44: li gp, 44; ; la x7, test_44_data; lw x7, 0(x7); beq a4, x7, test_44_success; la x7, fail; jr x7; .align 3; test_44_data: .quad ((4) & ((1 << (32 - 1) << 1) - 1)); test_44_success:
 # -------------- TEST END --------------
# -------------- TEST BEGIN --------------
li t0, 3
li t1, 3
li t2, 15
vsetvl zero, zero, t2
csrr a4, vstart
test_45: li gp, 45; ; la x7, test_45_data; lw x7, 0(x7); beq a4, x7, test_45_success; la x7, fail; jr x7; .align 3; test_45_data: .quad ((0) & ((1 << (32 - 1) << 1) - 1)); test_45_success:
csrr a4, vtype
test_46: li gp, 46; ; la x7, test_46_data; lw x7, 0(x7); beq a4, x7, test_46_success; la x7, fail; jr x7; .align 3; test_46_data: .quad ((15) & ((1 << (32 - 1) << 1) - 1)); test_46_success:
csrr a4, vl
test_47: li gp, 47; ; la x7, test_47_data; lw x7, 0(x7); beq a4, x7, test_47_success; la x7, fail; jr x7; .align 3; test_47_data: .quad ((4) & ((1 << (32 - 1) << 1) - 1)); test_47_success:
 # -------------- TEST END --------------
  bne x0, gp, pass; fail: fence; 1: beqz gp, 1b; sll gp, gp, 1; or gp, gp, 1; ecall; pass: fence; li gp, 1; ecall
unimp
  .data
.pushsection .tohost, "aw", @progbits; .align 6; .global tohost; tohost: .dword 0; .align 6; .global fromhost; fromhost: .dword 0; .popsection; .align 4; .global begin_signature; begin_signature:
 # Reserve space for test data.
resultdata:
  .zero 1024
testdata:
.align 4; .global end_signature; end_signature:
